// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Homeremedies": {
            "get": {
                "description": "Get all Homeremedies details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Homeremedies"
                ],
                "summary": "Get all Homeremedies details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Homeremedies"
                        }
                    }
                }
            }
        },
        "/NMK": {
            "get": {
                "description": "Get all NMK codes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NMK"
                ],
                "summary": "Get all NMK codes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NMK"
                        }
                    }
                }
            }
        },
        "/doctors": {
            "get": {
                "description": "Get all doctors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctors"
                ],
                "summary": "Get all doctors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DoctorData"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get users based on query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Addiction Type",
                        "name": "Addiction_Type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nasha Mukti Centre Code",
                        "name": "Nasha_Mukti_Centre_Code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Employment Status",
                        "name": "Employment_Status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Is Treatment Completed",
                        "name": "Is_Treatment_Completed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DoctorData": {
            "type": "object",
            "properties": {
                "ClinicAddress": {
                    "type": "string"
                },
                "ContactNumber": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "Docter_Code": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "ImageURL": {
                    "type": "string"
                },
                "IsVerified": {
                    "type": "boolean"
                },
                "Name": {
                    "type": "string"
                },
                "Specialization": {
                    "type": "string"
                },
                "_id": {
                    "type": "string"
                }
            }
        },
        "models.Homeremedies": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.NMK": {
            "type": "object",
            "properties": {
                "Address": {
                    "type": "string"
                },
                "Contact_Number": {
                    "type": "integer"
                },
                "District": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "Established_Year": {
                    "type": "integer"
                },
                "ImageURL": {
                    "type": "string"
                },
                "IsVerified": {
                    "type": "boolean"
                },
                "NMK_Code": {
                    "type": "string"
                },
                "NMK_Image": {
                    "type": "string"
                },
                "NMK_Verification_Image": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Owner_Name": {
                    "type": "string"
                },
                "Pincode": {
                    "type": "integer"
                },
                "State": {
                    "type": "string"
                },
                "_id": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "Addiction_Duration": {
                    "type": "integer"
                },
                "Addiction_Type": {
                    "type": "string"
                },
                "Age": {
                    "type": "integer"
                },
                "Counselling_Count": {
                    "type": "integer"
                },
                "Counsellor_Name": {
                    "type": "string"
                },
                "District": {
                    "type": "string"
                },
                "Duration_of-Treatment": {
                    "type": "integer"
                },
                "Employment_Status": {
                    "type": "integer"
                },
                "Gender": {
                    "type": "string"
                },
                "Guardian_Name": {
                    "type": "string"
                },
                "Is_Treatment_Completed": {
                    "type": "boolean"
                },
                "Joining_Date": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Nasha_Mukti_Centre_Address": {
                    "type": "string"
                },
                "Nasha_Mukti_Centre_Code": {
                    "type": "string"
                },
                "Nasha_Mukti_Centre_Name": {
                    "type": "string"
                },
                "State": {
                    "type": "string"
                },
                "Under_Treatment": {
                    "type": "boolean"
                },
                "_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
